name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *' # Runs at midnight every day
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install beautifulsoup4 requests python-dotenv

    - name: Update stars and forks count
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python update-stats.py

    - name: Check if index.html has changed
      id: check_changes
      run: |
        if git diff --name-only | grep -q "index.html"; then
          echo "index.html has changed."
          echo "::set-output name=changed::true"
        else
          echo "No changes in index.html."
          echo "::set-output name=changed::false"
        fi

    - name: Commit and push if index.html changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.email "paulsaegert@protonmail.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Auto-update stars and forks count"
        git push
